project_id = "dmlkjpjubneqhbqoxlct"

[functions.place-search]
verify_jwt = true

[functions.place-retrieve]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false